### ISSUE TITLE
特性请求：定时关闭所有运营消息

### ISSUE THREAD

**Issue by mingmxren** [GSWXXN/XMSFNotiChannel#4]
希望可以加一个定时关闭所有运营消息的功能

**Comment by GSWXXN** [comment]
是定时检查并关闭所有运营通知的开关吗, 还是在指定时间段关闭运营通知, 其余时间段开启?

**Comment by mingmxren** [comment]
定时检查并关闭所有运营通知，比如每天早上7点关闭所有运营通知。
以及能否加一个正则匹配功能，通知渠道符合规则的都可以一键关闭，大部分广告的通知还是有一定规律的，都有优惠，运营等关键字

**Comment by GSWXXN** [comment]
新版本已支持自定义搜索名称 55340aabbb4aed5fa40f59f3aaf30e6fd25d818c

定时检查功能暂时不打算加入
