### ISSUE TITLE
支持“营销消息通知”

### ISSUE THREAD

**Issue by Leojc** [GSWXXN/XMSFNotiChannel#5]
最近发现好几个软件通过“营销消息通知”发广告，作者考虑加一个吗？或者更进一步，能自定义搜索，能正则表达式匹配，搞成一个通知批量管理，那就更妙啦😁

**Comment by GSWXXN** [comment]
在做了, 但是进度可能会有点慢

**Comment by GSWXXN** [comment]
新版本已支持 55340aabbb4aed5fa40f59f3aaf30e6fd25d818c
