### ISSUE TITLE
闪退日志

### ISSUE THREAD

**Issue by Chameng** [GSWXXN/XMSFNotiChannel#7]
点击开始检测之后闪退
===============
[Device Brand]: blackshark
[Device Model]: SKW-A0
[Display]: SKYW2203210CN00MR1
[Android Version]: 11
[Android API Level]: 30
[System Locale]: zh_CN
[Process ID]: 20876
[CPU ABI]: none
[Package Name]: com.gswxxn.xmsfnotichannel
[Version Name]: 1.2
[Version Code]: 120
[Error Type]: JVM
[Crash Time]: 2023-04-02T22:37:58.579
[Stack Trace]:
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
	at f0.a.a(Unknown Source:141)
	at c0.i$a.e(Unknown Source:44)
	at n1.a.n(Unknown Source:8)
	at z1.e0.run(Unknown Source:100)
	at kotlinx.coroutines.scheduling.a$a.run(Unknown Source:78)
	Suppressed: z1.c0: [c1{Cancelling}@6250a1, Dispatchers.Main]

**Comment by GSWXXN** [comment]
试一下这个版本还闪退吗
https://wwrw.lanzoub.com/iidmh0rxo16h
密码:0000

**Comment by Chameng** [comment]
> 试一下这个版本还闪退吗 https://wwrw.lanzoub.com/iidmh0rxo16h 密码:0000

啊呀刚看到，我看发布的1.2.1已经不闪退了
