### ISSUE TITLE
请增加隐藏桌面图标功能

### ISSUE THREAD

**Issue by razilong** [GSWXXN/XMSFNotiChannel#8]

**Comment by GSWXXN** [comment]
这个应用的 Xposed 部分只是为程序本身放行权限, 主要功能并不是靠 Xposed 实现的. 

一般 Xposed 模块的 UI 界面都是对其 Hook 功能的配置, 所以隐藏桌面图标是很正常的. 

而我更希望是把这个应用当做一个普通 App 对待. 在它刚发出来的时候, 我对它的定义是一个一次性应用, 用完直接删了就好. 所以暂时不考虑增加隐藏桌面图标功能. ~(除非有人 pr~
